#!/bin/sh
set -eu

export VAULT_ADDR="${VAULT_ADDR:-http://vault:8200}"
export VAULT_TOKEN="${VAULT_TOKEN:?VAULT_TOKEN must be set}"

until vault status >/dev/null 2>&1; do
  sleep 1
done

if ! vault secrets list -format=json | grep -q '"secret/"'; then
  vault secrets enable -path=secret -version=2 kv
fi

vault kv put secret/fraud-engine \
  FRAUD_ENGINE_POSTGRES_USER="${FRAUD_ENGINE_POSTGRES_USER:?FRAUD_ENGINE_POSTGRES_USER must be set}" \
  FRAUD_ENGINE_POSTGRES_PASSWORD="${FRAUD_ENGINE_POSTGRES_PASSWORD:?FRAUD_ENGINE_POSTGRES_PASSWORD must be set}" \
  REDIS_PASSWORD="${REDIS_PASSWORD:?REDIS_PASSWORD must be set}" \
  GEMINI_API_KEY="${GEMINI_API_KEY:?GEMINI_API_KEY must be set}" \
  EDGE_GATEWAY_JWT_ISSUER_URI="${EDGE_GATEWAY_JWT_ISSUER_URI:?EDGE_GATEWAY_JWT_ISSUER_URI must be set}" \
  EDGE_GATEWAY_JWT_JWK_SET_URI="${EDGE_GATEWAY_JWT_JWK_SET_URI:?EDGE_GATEWAY_JWT_JWK_SET_URI must be set}" \
  DASHBOARD_OIDC_CLIENT_ID="${DASHBOARD_OIDC_CLIENT_ID:?DASHBOARD_OIDC_CLIENT_ID must be set}" \
  DASHBOARD_OIDC_CLIENT_SECRET="${DASHBOARD_OIDC_CLIENT_SECRET:?DASHBOARD_OIDC_CLIENT_SECRET must be set}" \
  KAFKA_SECURITY_PROTOCOL="${KAFKA_SECURITY_PROTOCOL:-SASL_PLAINTEXT}" \
  KAFKA_SASL_MECHANISM="${KAFKA_SASL_MECHANISM:-SCRAM-SHA-512}" \
  KAFKA_SASL_USERNAME="${KAFKA_SASL_USERNAME:-fraud-engine-app}" \
  KAFKA_SASL_PASSWORD="${KAFKA_SASL_PASSWORD:-local-dev-kafka-sasl-password}"
